export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const INCREMENT_PRODUCT_CART = 'INCREMENT_PRODUCT_CART';
